name: 'Build docker image'

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

env:
  IMAGE_NAME: "flipperdevices/firmware-report-server"

jobs:
  build:
    runs-on: [self-hosted,FlipperZeroShell]
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Set image tag'
        run: |
          IMAGE_TAG=latest
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            REF=${{ github.ref }};
            TAG_FULL=${REF#refs/*/};
            IMAGE_TAG=${TAG_FULL//\//_};
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: 'Build docker image'
        run: |
          docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" .

      - name: 'Upload docker image'
        run: |
          docker push "$IMAGE_NAME:$IMAGE_TAG"
